apiVersion: v1
kind: Secret
metadata:
  name: woodpecker-config-service
  namespace: woodpecker
type: Opaque
stringData:
  webhook_public_key: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEAjDSscf8Ckon3wc9o77iEGcillyVU2NEwcnUXdARlERM=
    -----END PUBLIC KEY-----
